version: '3.4'

services:
  zipkin-server:
    restart: always
    image: openzipkin/zipkin:2.23.16
    depends_on:
      - rabbit-mq
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
    ports:
      - 9411:9411
    networks:
      - ale-network
   
  rabbit-mq:
    image: rabbitmq:3.8.14-management
    ports: 
      - 5672:5672
      - 15672:15672
    networks:
      - ale-network
   
  register-server:
    image: aleharitos/register-server:0.0.1-SNAPSHOT
    ports: 
      - 8761:8761
    networks:
      - ale-network   
     
  api-gateway:
    image: aleharitos/api-gateway:0.0.1-SNAPSHOT
    ports: 
      - 8765:8765
    depends_on:
      - register-server
      - rabbit-mq
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://register-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
    networks:
      - ale-network
   
  person-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3308:3308
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ale123
      MYSQL_USER: docker
      MYSQL_PASSWORD: ale123
      MYSQL_DATABASE: person_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    expose:
      - 3308
    networks:
      - ale-network
      
  vehicle-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3310:3310
    expose:
      - 3310
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: ale123
      MYSQL_USER: docker
      MYSQL_PASSWORD: ale123
      MYSQL_DATABASE: vehicle_service
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3310
    networks:
      - ale-network
      
  traffic-ticket-db:
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports: 
      - 3312:3312
    expose: 
      - 3312
    environment:
      TZ: America/Sao_Paulo
      MYSQL_PASSWORD: ale123
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: ale123
      MYSQL_DATABASE: traffic_ticket_service
      MYSQL_HOST: '%'
      MYSQL_TCP_PORT: 3312
    networks: 
      - ale-network
  
  person-service:
    image: aleharitos/person-service
    restart: always
    build: 
      context: .
      dockerfile: person-service/Dockerfile
    ports: 
      - 8000:8000
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://register-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.URL: jdbc:mysql://person-db:3308/person_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: ale123
      SPRING.FLYWAY.URL: jdbc:mysql://person-db:3308/person_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: ale123
    depends_on:
      - register-server
      - person-db
      - rabbit-mq
    networks: 
      - ale-network
      
  vehicle-service:
    image: aleharitos/vehicle-service
    restart: always
    build: 
      context: .
      dockerfile: vehicle-service/Dockerfile
    ports:
      - 8100:8100
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://register-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.PASSWORD: ale123
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.URL: jdbc:mysql://vehicle-db:3310/vehicle_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.URL: jdbc:mysql://vehicle-db:3310/vehicle_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: ale123
    depends_on:
      - register-server
      - vehicle-db
      - rabbit-mq
    networks:
      - ale-network
      
      
  traffic-ticket-service:
    image: aleharitos/traffic-ticket-service
    restart: always
    build: 
      context: .
      dockerfile: traffic-ticket-service/Dockerfile
    ports:
      - 8200:8200
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://register-server:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/
      RABBIT_URI: amqp://guest:guest@rabbit-mq:5672
      SPRING_RABBITMQ_HOST: rabbit-mq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SPRING.DATASOURCE.PASSWORD: ale123
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.URL: jdbc:mysql://traffic-ticket-db:3312/traffic_ticket_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.URL: jdbc:mysql://traffic-ticket-db:3312/traffic_ticket_service?useSSL=false&useTimezone=true&serverTimezone=UTC&enabledTLSProtocols=TLSv1.2
      SPRING.FLYWAY.USER: root
      SPRING.FLYWAY.PASSWORD: ale123
    depends_on:
      - register-server
      - traffic-ticket-db
      - rabbit-mq
    networks:
      - ale-network
      
 
networks:
  ale-network:
    driver: bridge