server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  sleuth:
    sampler:
      probability: 0.05
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: person-service
        uri: lb://person-service
        predicates:
        - Path=/person/**
      - id: vehicle-service
        uri: lb://vehicle-service
        predicates:
        - Path=/vehicle/**
      - id: traffic-ticket-service
        uri: lb://traffic-ticket-service
        predicates:
        - Path=/traffic-ticket/**
      - id: openapi
        uri: lb://api-gateway
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
