server:
  port: 8200
spring:
  application:
    name: traffic-ticket-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/traffic_ticket_service?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    user: root
    password: 123456
    url: jdbc:mysql://localhost:3307/traffic_ticket_service?useTimezone=true&serverTimezone=UTC
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
