server:
  port: 8000
spring:
  application:
    name: person-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3307/person_service?useTimezone=true&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  flyway:
    user: root
    url: jdbc:mysql://localhost:3307/person_service?useTimezone=true&serverTimezone=UTC
    password: 123456
  jackson:
    default-property-inclusion: non-null
    serialization:
      fail-on-empty-beans: false
  sleuth:
    sampler:
      probability: 0.05
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      default: 
        max-attempts: 5
        wait-duration: 1s
  ratelimiter:
    instances:
      default:
        limit-for-period: 150
        limit-refresh-period: 12s
springdoc:
  api-docs:
    path: person/v3/api-docs
